// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.CustomerAPI.Data;

#nullable disable

namespace Services.CustomerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.CustomerAPI.Models.Customer", b =>
                {
                    b.Property<int>("Cus_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cus_Id"));

                    b.Property<string>("Cus_Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Cus_Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cus_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cus_Gender")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Cus_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cus_Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cus_Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("Cus_Status")
                        .HasColumnType("bit");

                    b.HasKey("Cus_Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Cus_Id = 1,
                            Cus_Avatar = "https://example.com/avatar.jpg",
                            Cus_Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cus_Email = "johndoe@example.com",
                            Cus_Gender = "M",
                            Cus_Name = "John Doe",
                            Cus_Password = "password123",
                            Cus_Phone = "1234567890",
                            Cus_Status = true
                        },
                        new
                        {
                            Cus_Id = 2,
                            Cus_Avatar = "https://example.com/avatar.jpg",
                            Cus_Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Cus_Email = "johndoe@example.com",
                            Cus_Gender = "M",
                            Cus_Name = "Trà My",
                            Cus_Password = "password123",
                            Cus_Phone = "1234567890",
                            Cus_Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
