// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.ProductAPI.Data;

#nullable disable

namespace Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241112151749_Product")]
    partial class Product
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bra_Id")
                        .HasColumnType("int");

                    b.Property<int>("Cat_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nat_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Sup_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bra_Id = 1,
                            Cat_Id = 1,
                            Name = "Áo thun co giãn",
                            Nat_Id = 1,
                            Status = true,
                            Sup_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Bra_Id = 1,
                            Cat_Id = 2,
                            Name = "Áo thun Halloween",
                            Nat_Id = 1,
                            Status = true,
                            Sup_Id = 2
                        });
                });

            modelBuilder.Entity("Services.ProductAPI.Models.ProductVariation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Col_Id")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("money");

                    b.Property<string>("Pic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Pro_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Siz_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Pro_Id");

                    b.ToTable("ProductVariations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Col_Id = 1,
                            Desc = "Áo thun cao cấp, siêu bền đẹp.",
                            Discount = 10,
                            ImportPrice = 40000m,
                            Pic = "https://res.cloudinary.com/dt46dvdeu/image/upload/v1730974763/demowebHKH/aothun/atpe0pdkpyekfcmb981n.jpg",
                            Price = 50000m,
                            Pro_Id = 1,
                            Quantity = 200,
                            Siz_Id = 1,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Col_Id = 1,
                            Desc = "Áo thun hoá trang DonalTrump cao cấp, siêu bền đẹp.",
                            Discount = 8,
                            ImportPrice = 800000m,
                            Pic = "https://res.cloudinary.com/dt46dvdeu/image/upload/v1730974762/demowebHKH/aothun/x3gsg9qmgtmrqxq4cnqn.jpg",
                            Price = 990000m,
                            Pro_Id = 2,
                            Quantity = 100,
                            Siz_Id = 1,
                            Status = true
                        });
                });

            modelBuilder.Entity("Services.ProductAPI.Models.ProductVariation", b =>
                {
                    b.HasOne("Services.ProductAPI.Models.Product", "Product")
                        .WithMany("ProductVariations")
                        .HasForeignKey("Pro_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Services.ProductAPI.Models.Product", b =>
                {
                    b.Navigation("ProductVariations");
                });
#pragma warning restore 612, 618
        }
    }
}
