// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.AddressAPI.Data;

#nullable disable

namespace Services.AddressAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241107062301_M_Address_Db")]
    partial class M_Address_Db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.AddressAPI.Models.Address", b =>
                {
                    b.Property<int>("Address_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Address_ID"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Address_ID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Address_ID = 1,
                            AddressLine = "123 Main St, District 1",
                            Customer_ID = 1,
                            District = "District 1",
                            IsDefault = true,
                            Name = "John Doe",
                            Phone = "0123456789",
                            Province = "Hồ Chí Minh",
                            Ward = "Ward 1"
                        },
                        new
                        {
                            Address_ID = 2,
                            AddressLine = "456 Second Ave, District 3",
                            Customer_ID = 2,
                            District = "District 3",
                            IsDefault = false,
                            Name = "Trà My",
                            Phone = "0987654321",
                            Province = "Hà Nội",
                            Ward = "Ward 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
