// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.CartItemAPI.Data;

#nullable disable

namespace Services.CartItemAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241106192710_TenMigration")]
    partial class TenMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.CartItemAPI.Models.CartItem", b =>
                {
                    b.Property<int>("Item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Item_Id"));

                    b.Property<int>("Cus_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Item_Id");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Item_Id = 1,
                            Cus_Id = 1,
                            Price = 20000m,
                            Quantity = 2
                        },
                        new
                        {
                            Item_Id = 2,
                            Cus_Id = 1,
                            Price = 90000m,
                            Quantity = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
